---
title: "March Madness Basketball Turniment"
author: "Sabrina Ball and Joe Despres"
date: "updated: `r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

background-image: url(https://upload.wikimedia.org/wikipedia/en/2/28/March_Madness_logo.svg)

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)

merged <- readr::read_csv(here::here("data", "merged.csv"))
ids <- readr::read_csv(here::here("data", "ids.csv"))
s2021 <- readr::read_csv(here::here("data", "s2021.csv"))
```

<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 4em 1em 4em;
}
</style>

---
```{r}
logistic_predictor_fn <- function (team_1_id, team_2_id) {
  stats_team_1 <- filter(s2021, TeamID == team_1_id)
  stats_team_2 <- filter(s2021, TeamID == team_2_id) %>% 
                         rename_all(~ paste0("opposing",.)) 
  bound_cols <- bind_cols(stats_team_1, stats_team_2)
  pred <- predict(logistic_fit, newdata = bound_cols, type = "response")
  
  return(pred)
}

logistic_predictor <- purrr::possibly(.f = logistic_predictor_fn, otherwise = "ERROR")
```

---

```{r}
logistic_fit <- glm(win ~ x3fg + opposingx3fg +
                      # field goal pct
                      fg_percent + opposingfg_percent +
                      # free throws
                      ft_percent + opposingft_percent +
                      # rebound per game
                      rpg + opposingrpg +
                      # steels
                      st + opposingst +
                      #turnover
                      to + opposingto +
                      # blocks
                      opposingbkpg + bkpg,
                    data = merged, family = "binomial")
```
---
`r chunk_reveal("logistic")`

```{r logistic}
ids %>%
  mutate(predicted_probs = map2_dbl(.x = ids$teamid,
                                    .y = ids$otherid,
                                    .f = logistic_predictor)) %>% 
   mutate(
    predicted_winner = if_else(predicted_probs > .5, team, other_team),
    predicted_winner_probs = if_else(predicted_probs > .5, predicted_probs , 1 - predicted_probs),
    predicted_loser_probs = 1 - predicted_winner_probs,
    prediction_points = predicted_winner_probs - predicted_loser_probs,
    .after = game
  )

```

--- 

`r chunk_reveal("my_cars")`

```{r my_cars, include = FALSE}
cars %>%
  filter(speed > 4) %>%
  ggplot() +
  aes(x = speed) + #BREAK
  aes(y = dist) + #BREAK
  geom_point(
    alpha = .8, 
    color = "blue" 
    ) + 
  aes(size = speed) #BREAK
```
